import { useRouter } from "next/router";
import { useEffect } from "react";
import BoardWritePage from "./board/write";
import BoardListPage from "./board/list";
import Head from "next/head";

export default function Home() {


  return <div>
    <Head>
        <title>creator-connect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.jpg" type="image/jpeg"/>
      </Head>
    <BoardListPage/>
    </div>;
}